version: "3.9"

services:
  nginx:
    container_name: otus-nginx
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - php
    volumes:
      - "./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    networks:
      - otus-lesson-microservices

  php:
    container_name: otus-php
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    volumes:
      - ".:/var/www/html"
    networks:
      - otus-lesson-microservices

  mysql:
    container_name: otus-mysql
    build:
      context: .
      dockerfile: .docker/mysql/Dockerfile
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: otus
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: localhost
    volumes:
      - otus-lesson-mysql-data:/var/lib/mysql
    networks:
      - otus-lesson-microservices

volumes:
  otus-lesson-mysql-data: { }

networks:
  otus-lesson-microservices:
    external: true