version: "3.9"

services:
  nginx:
    container_name: aldmi-nginx
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - php
    volumes:
      - "./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    networks:
      - aldmi-app-microservices

  php:
    container_name: aldmi-php
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    volumes:
      - ".:/var/www/html"
    networks:
      - aldmi-app-microservices

  mysql:
    container_name: aldmi-mysql
    build:
      context: .
      dockerfile: .docker/mysql/Dockerfile
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: microservice
      MYSQL_USER: ${DB_USERNAME:-aldmi}
      MYSQL_PASSWORD: ${DB_PASSWORD:-aldmi}
      MYSQL_ROOT_PASSWORD: 'secret'
      MYSQL_ROOT_HOST: "%"
    volumes:
      - aldmi-app-mysql-data:/var/lib/mysql
    networks:
      - aldmi-app-microservices

volumes:
  aldmi-app-mysql-data: { }

networks:
  aldmi-app-microservices:
    external: true